import json
import os

PROJECT_DIR = os.path.dirname(os.path.abspath(__file__))
ENTRIES_FILE = os.path.join(PROJECT_DIR, "entries.json")
OUTPUT_FILE = os.path.join(PROJECT_DIR, "game_guide.js")

with open(ENTRIES_FILE, "r", encoding="utf-8") as f:
    data = json.load(f)

lines = []
lines.append("const ENTRIES_DATA = " + json.dumps(data, ensure_ascii=False))
lines.append(";")
lines.append("")
lines.append("function mdToHtml(text) {")
lines.append("    if (!text) return '';")
lines.append("    var lines = text.split('\\n');")
lines.append("    var html = '';")
lines.append("    var inP = false;")
lines.append("    for (var i = 0; i < lines.length; i++) {")
lines.append("        var line = lines[i];")
lines.append("        if (line.trim() === '') {")
lines.append("            if (inP) { html += '</p>'; inP = false; }")
lines.append("            continue;")
lines.append("        }")
lines.append("        line = line.replace(/\\*\\*(.+?)\\*\\*/g, '<strong>$1</strong>');")
lines.append("        line = line.replace(/\\*(.+?)\\*/g, '<em>$1</em>');")
lines.append("        if (!inP) { html += '<p>'; inP = true; } else { html += '<br>'; }")
lines.append("        html += line;")
lines.append("    }")
lines.append("    if (inP) html += '</p>';")
lines.append("    return html;")
lines.append("}")
lines.append("")
lines.append("let guideCurrentCat = null;")
lines.append("let guideCurrentEntry = null;")
lines.append("")
lines.append("function openGameGuideModal() {")
lines.append("    document.getElementById('gameGuideModal').style.display = 'flex';")
lines.append("    renderGuideTree();")
lines.append("    renderEntryList();")
lines.append("    if (ENTRIES_DATA.categories.length > 0) selectCategory(0);")
lines.append("}")
lines.append("")
lines.append("function closeGameGuideModal() {")
lines.append("    document.getElementById('gameGuideModal').style.display = 'none';")
lines.append("}")
lines.append("")
lines.append("function renderGuideTree() {")
lines.append("    var tree = document.getElementById('guideTree');")
lines.append("    tree.innerHTML = '';")
lines.append("    ENTRIES_DATA.categories.forEach(function(cat, idx) {")
lines.append("        var item = document.createElement('div');")
lines.append("        item.className = 'guide-tree-item' + (guideCurrentCat === idx ? ' active' : '');")
lines.append("        item.textContent = cat.icon + ' ' + cat.title;")
lines.append("        item.addEventListener('click', function() { selectCategory(idx); });")
lines.append("        tree.appendChild(item);")
lines.append("    });")
lines.append("}")
lines.append("")
lines.append("function selectCategory(idx) {")
lines.append("    guideCurrentCat = idx;")
lines.append("    guideCurrentEntry = null;")
lines.append("    renderGuideTree();")
lines.append("    renderEntryList();")
lines.append("}")
lines.append("")
lines.append("function renderEntryList() {")
lines.append("    var list = document.getElementById('guideEntryList');")
lines.append("    list.innerHTML = '';")
lines.append("    if (guideCurrentCat === null) return;")
lines.append("    var cat = ENTRIES_DATA.categories[guideCurrentCat];")
lines.append("    cat.entries.forEach(function(entry, idx) {")
lines.append("        var item = document.createElement('div');")
lines.append("        item.className = 'entry-item' + (guideCurrentEntry === idx ? ' active' : '');")
lines.append("        item.textContent = entry.title;")
lines.append("        item.addEventListener('click', function() { selectEntry(idx); });")
lines.append("        list.appendChild(item);")
lines.append("    });")
lines.append("}")
lines.append("")
lines.append("function selectEntry(idx) {")
lines.append("    guideCurrentEntry = idx;")
lines.append("    renderEntryList();")
lines.append("    var cat = ENTRIES_DATA.categories[guideCurrentCat];")
lines.append("    var entry = cat.entries[idx];")
lines.append("    var content = document.getElementById('guideEntryContent');")
lines.append("    var html = '<h1>' + entry.title + '</h1>';")
lines.append("    if (entry.image) {")
lines.append("        html += '<img src=\"' + entry.image + '\" alt=\"\" class=\"entry-image\">';")
lines.append("    }")
lines.append("    html += '<div class=\"entry-body\">' + mdToHtml(entry.content) + '</div>';")
lines.append("    content.innerHTML = html;")
lines.append("}")
lines.append("")
lines.append("function initGameGuide() {")
lines.append("    var btn = document.getElementById('gameGuideBtn');")
lines.append("    var closeBtn = document.getElementById('closeGameGuideBtn');")
lines.append("    if (btn) btn.addEventListener('click', openGameGuideModal);")
lines.append("    if (closeBtn) closeBtn.addEventListener('click', closeGameGuideModal);")
lines.append("}")
lines.append("")
lines.append("if (document.readyState === 'loading') {")
lines.append("    document.addEventListener('DOMContentLoaded', initGameGuide);")
lines.append("} else {")
lines.append("    initGameGuide();")
lines.append("}")

with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
    f.write("\n".join(lines))

print("导出完成: " + OUTPUT_FILE)
